### ISSUE TITLE
서버에서 컴파일 후 돌리려는데 안돌아감

### ISSUE THREAD

**Issue by alxest** [snu-sf/CompCert#33]
./myccomp tmp.c
이렇게 하면
/usr/bin/ld: cannot find -lcompcert
collect2: error: ld returned 1 exit status
이런 에러가 뜹니다.

**Comment by jeehoonkang** [comment]
어떤 서버에서 myccomp를 어떻게 얻었는지 더 상세한 정보 부탁합니다.
2015. 8. 17. 오후 10:32에 "YoungJu Song" notifications@github.com님이 작성:

**Comment by alxest** [comment]
윤승이형 도움으로 해결했는데
- build 디렉토리에 lib 라는 빈 디렉토리 만들고 make install 다시 하니까 libcompcert.a 라는 파일이 나옴
- 컴파일 옵션에 -L 로 그 위치를 줌 (단 ~/ 는 인식을 못함)
- -o 로 아웃풋 파일 이름을 주는데 tmp.o 로 하니까 왠지 모르겠지만 안되고 다른 이름으로 하니 됨
