### ISSUE TITLE
Fix sepcomp1 branch: updating selection's proof

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/CompCert#6]
- `sepcomp1` branch covers the part I.
- Since we `cherry-pick`ed mainline CompCert's patch for helper functions, we have to update the proof. So now `sepcomp1` branch is broken: `sepcomp/backend/Selectionproof_sepcomp.v` is not compiled.
- Please fix it and commit.

Jeehoon

**Comment by jeehoonkang** [comment]
- I will prepare for part II branch, `sepcomp2`, after this issue is resolved.
- Basically I will move `sepcomp` branch into `sepcomp2`.

**Comment by kim-yoonseung** [comment]
CompCert 패치를 보면, sel_program 함수가 전체 프로그램을 받아서 check_helpers 한 번 돌리고 변환을 시작하는데요, sel_program 안에서 sel_function이 불립니다.

우리 Selectionproof_sepcomp.v 에서의 가정(TRANSF)은 sel_function을 바로 쓰는데, 이걸 sel_program을 쓰는 원래 compcert 버전으로 바꿔도 괜찮나요?

**Comment by jeehoonkang** [comment]
check helpers를 가정하고 증명해도 좋을듯 해요
